name: "Publish Documentation to NIST Pages"

on: [push, pull_request, delete]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/NISTtheDocs2Death@0.4
        with:
          docs-folder: docs/
          formats: ''
          pip-requirements: 'docs/requirements.txt'